### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Template' not found

### ISSUE THREAD

**Issue by oleteacher** [kbrmedia/Simple-PHP-Template-System#2]
Saw your work (url shortner) on evanto. So exporing your work here:)

Cannot get this to work. Looking at the files in src folder. Changed the index.php to reflect demo,tpl.

Now all I get is:

`Fatal error: Uncaught Error: Class 'Template' not found in /SiteBuilders/Simple-PHP-Template-System/src/index.php:3 Stack trace: #0 {main} thrown in /SiteBuilders/Simple-PHP-Template-System/src/index.php on line 3`

What am I missing?

Thanks!

**Comment by kbrmedia** [comment]
Hello

Make sure to correct the path to the Template.class.php file.

**Comment by oleteacher** [comment]
Thanks. Should have caught that but distracted by my classroom noise:)
